// Generated by gencpp from file move/Move.msg
// DO NOT EDIT!


#ifndef MOVE_MESSAGE_MOVE_H
#define MOVE_MESSAGE_MOVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move
{
template <class ContainerAllocator>
struct Move_
{
  typedef Move_<ContainerAllocator> Type;

  Move_()
    : direction()
    , power(0)  {
    }
  Move_(const ContainerAllocator& _alloc)
    : direction(_alloc)
    , power(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;

   typedef int32_t _power_type;
  _power_type power;





  typedef boost::shared_ptr< ::move::Move_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move::Move_<ContainerAllocator> const> ConstPtr;

}; // struct Move_

typedef ::move::Move_<std::allocator<void> > Move;

typedef boost::shared_ptr< ::move::Move > MovePtr;
typedef boost::shared_ptr< ::move::Move const> MoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move::Move_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move::Move_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move::Move_<ContainerAllocator1> & lhs, const ::move::Move_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.power == rhs.power;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move::Move_<ContainerAllocator1> & lhs, const ::move::Move_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move::Move_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move::Move_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move::Move_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move::Move_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move::Move_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move::Move_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move::Move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efe20d682e9038d97b30d36a75eea378";
  }

  static const char* value(const ::move::Move_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefe20d682e9038d9ULL;
  static const uint64_t static_value2 = 0x7b30d36a75eea378ULL;
};

template<class ContainerAllocator>
struct DataType< ::move::Move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move/Move";
  }

  static const char* value(const ::move::Move_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move::Move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string direction\n"
"int32 power\n"
;
  }

  static const char* value(const ::move::Move_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move::Move_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Move_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move::Move_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move::Move_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
    s << indent << "power: ";
    Printer<int32_t>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_MESSAGE_MOVE_H
